import { useState } from "react";
import { useForm } from "react-hook-form";
import { Input } from "@nextui-org/input";
import { Button } from "@nextui-org/button";
import { jsPDF } from "jspdf";

interface FormData {
  petType: string;
  age: number;
  weight: number;
}

const calculateNutrition = (age: number, weight: number, petType: string) => {
  if (petType.toLowerCase() === "dog") {
    return {
      calories: weight * 30 + 70,
      protein: weight * 2,
    };
  } else if (petType.toLowerCase() === "cat") {
    return {
      calories: weight * 25 + 60,
      protein: weight * 1.5,
    };
  } else {
    return { calories: 0, protein: 0 };
  }
};

const Calculator = () => {
  const { register, handleSubmit } = useForm<FormData>();
  const [nutrition, setNutrition] = useState({ calories: 0, protein: 0 });

  const onSubmit = (data: FormData) => {
    const result = calculateNutrition(data.age, data.weight, data.petType);
    setNutrition(result);

    const doc = new jsPDF();
    doc.setFont("helvetica", "normal");

    // Add a title
    doc.setFontSize(22);
    doc.setTextColor(40, 40, 40); // Set title color
    doc.text(`Nutrition Report for ${data.petType}`, 10, 20);
    
    // Draw a line
    doc.setLineWidth(1);
    doc.line(10, 25, 200, 25); // Draw a line across the page

    // Add the report details
    doc.setFontSize(14);
    doc.setTextColor(60, 60, 60); // Set details color
    doc.text(`Age: ${data.age} years`, 10, 40);
    doc.text(`Weight: ${data.weight} kg`, 10, 50);
    doc.text(`Estimated Calories: ${result.calories} kcal/day`, 10, 60);
    doc.text(`Protein Needs: ${result.protein} g/day`, 10, 70);

    // Add a footer
    doc.setFontSize(10);
    doc.setTextColor(150, 150, 150); // Footer color
    doc.text("Generated by Your Pet Nutrition App", 10, 280);

    // Save the PDF
    doc.save(`${data.petType}_nutrition_report.pdf`);
  };

  return (
    <div className="flex flex-col lg:flex-row gap-5 justify-center">
      <div className="p-2 lg:p-6 lg:w-1/2 bg-white shadow-lg">
        <h1 className="text-center my-2 font-bold text-2xl">Calculator</h1>
        <form
          onSubmit={handleSubmit(onSubmit)}
          className="flex flex-col space-y-6 max-w-md mx-auto"
        >
          <Input
            {...register("petType")}
            placeholder="Pet Type (dog/cat)"
            label="Pet Type"
            required
          />
          <Input
            {...register("age")}
            type="number"
            placeholder="Age in years"
            label="Pet Age"
            required
          />
          <Input
            {...register("weight")}
            type="number"
            placeholder="Weight in kg"
            label="Pet Weight"
            required
          />
          <Button type="submit" className="bg-[#148d8c] text-white dark:text-white">
            Download PDF
          </Button>
        </form>
      </div>

      <div className="lg:w-1/2 w-full">
        <div className="grid grid-cols-2 gap-1 p-2 md:grid-cols-3 lg:grid-cols-2">
       

          <div
            className="bg-center bg-no-repeat bg-cover aspect-auto rounded col-span-2 md:col-span-3"
            style={{
              backgroundImage: 'url("https://img.freepik.com/premium-photo/cat-food-graphs_23-2151537804.jpg?w=826")',
              height: '200px',
            }}
          ></div>

          <div
            className="bg-center bg-no-repeat bg-cover aspect-auto rounded"
            style={{
              backgroundImage: 'url("https://img.freepik.com/premium-photo/cat-near-bowl-full-dry-cat-food_185667-12363.jpg?w=1060")',
              height: '150px',
            }}
          ></div>

          <div
            className="bg-center bg-no-repeat bg-cover aspect-auto rounded"
            style={{
              backgroundImage: 'url("https://img.freepik.com/premium-photo/cat-food-graphs_23-2151537822.jpg?w=1380")',
              height: '150px',
            }}
          ></div>
        </div>
      </div>
    </div>
  );
};

export default Calculator;
